---
title: "Stats with R for Clinical Researchers"
author: "Albert Cobos (acoboscarbo@gmail.com)"
date: "28-10-2025"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE,
                      comment = NA)

```

\
\

Recommended pre-course reading: [Statistical Inference](https://acobos.github.io/DA/statistical-inference.html).

\
\


## Some common statistical tests & methods

|  |  |
|------------------------------------|------------------------------------|
| [Categorical variables, independent samples](https://acobos.github.io/CDB_ed4/1_1_categ_indep.html#1) |[Solution to exes](1_1_categ_indep_exe_solution.R) |  
| [Categorical variables, paired samples](https://acobos.github.io/CDB_ed4/1_2_categ_paired.html) |[Solution to exes](1_2_categ_paired_exe_solution.R)  | 
| [Quantitative variables, independents samples](https://acobos.github.io/CDB_ed4/1_3_quant_indep.html) |[Solution to exes](1_3_quant_indep_exe_solution.R) |
| [Quantitative variables, paired samples](https://acobos.github.io/CDB_ed4/1_4_quant_paired.html)  |[Solution to exes](1_4_quant_paired_exe_solution.R)  |
| [Analysis of variance](https://acobos.github.io/CDB_ed4/1_5_anova.html) |[Solution to exes](1_5_anova_exe_solution.R)  |
| [Permutation tests and the bootstrap](https://acobos.github.io/CDB_ed4/1_6_bootstrap.html)  |[Solution to exes](1_6_bootstrap_exe_solution.R) |
| [ROC curves and AUC](https://acobos.github.io/CDB_ed4/1_7_roc_auc.html) |[Solution to exes](1_7_roc_auc_exe_solution.R)  |
| [Association](https://acobos.github.io/CDB_ed4/1_8_association.html) | [Solution to exes](1_8_association_exe_solution.R) |

\

## Statistical modelling

|  |  |
|------------------------------------|------------------------------------|
| [General linear model: coefficients and GOF](https://acobos.github.io/CDB_ed4/2_1_glm_1.html) |[Solution to exes](2_1_glm_1_exe_solution.R)  |
| [General linear model: model assumptions](https://acobos.github.io/CDB_ed4/2_2_glm_2.html) |[Solution to exes](2_2_glm_2_exe_solution.R)  |
| [General linear model: confounding and interaction](https://acobos.github.io/CDB_ed4/2_3_glm_3.html) |[Solution to exes](2_3_glm_3_exe_solution.R)  |
| [Logistic regression model 1](https://acobos.github.io/CDB_ed4/2_4_logistic_1.html) |[Solution to exes](2_4_logistic_1_exe_solution.R)  |
| [Logistic regression model 2](https://acobos.github.io/CDB_ed4/2_5_logistic_2.html) |[Solution to exes](2_5_logistic_2_exe_solution.R)   |
| [Survival analysis 1: Kaplan-Meier estimates and log-rank test](https://acobos.github.io/CDB_ed4/2_6_survival.html) |[Solution to exes](2_6_survival_exe_solution.R)  |
| [Survival analysis 2: Cox proportional hazards model](https://acobos.github.io/CDB_ed4/2_7_cox.html) |[Solution to exes](2_7_cox_exe_solution.R)   |

- [Survival analysis/plots cheat sheet](https://rpkgs.datanovia.com/survminer/survminer_cheatsheet.pdf)

\

## Readings 

### General

- A couple of free online books this course is loosely based on:
  - [Data Analysis for Clinical Researchers (Chap. 7 and 8)](https://acobos.github.io/DA/index.html). 
  - [Statistical Modeling for Clinical Researchers](https://acobos.github.io/SM/index.html).

- [A Student’s guide to R](https://cran.r-project.org/doc/contrib/Horton+Pruim+Kaplan_MOSAIC-StudentGuide.pdf): free book on introductory and intermediate statistics with R.  

- [The Elements of statistical learning](https://hastie.su.domains/ElemStatLearn/), by T. Hastie, R. Tibshirani and J. Friedman. A very good book on both classical and modern modeling methods, such as random forest, support vector machines or neural networks. Freely available as pdf.


### Specific

- Do not use histograms to assess normality: [find out why](https://statisticsbyjim.com/basics/assessing-normality-histograms-probability-plots/).

- [Packages for ROC curves](https://rviews.rstudio.com/2019/03/01/some-r-packages-for-roc-curves/)






- [Introduction to Bootstrapping in Statistics with an Example](https://statisticsbyjim.com/hypothesis-testing/bootstrapping/). A short and intuitive introduction to the bootstrap.
